<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Alter the node add/edit form to include admin setting for displaying RSVPBlock with content
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function rsvp_list_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $node = $form_state->getFormObject()->getEntity();
  $config = Drupal::config('rsvp_list.settings');
  $node_type = $node->getType();
  $types = $config->get('allowed_types');

  // RSVP Options for administrators
  if (in_array($node_type, $types)) {
    $form['rsvp_list'] = array(
      '#type' => 'details',
      '#title' => t('RSVP Collection'),
      '#access' => Drupal::currentUser()->hasPermission('administer rsvp_list'),
      '#group' => 'advanced',
      '#weight' => 100,
    );

    /** @var EnablerService $enabler */
    $enabler = Drupal::service('rsvp_list.enabler');
    $form['rsvp_list']['rsvp_list_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Collect RSVP e-mail addresses for this node.'),
      '#default_value' => $enabler->getNodeStatus($node),
    ];

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'rsvp_list_form_node_form_submit';
      }
    }
  }
}

/**
 * Form submission handler for RSVP item field on the node form.
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @see rsvp_list_form_node_form_alter()
 *
 */
function rsvp_list_form_node_form_submit(array $form, FormStateInterface $form_state)
{
  /** @var EnablerService $enabler */
  $enabler = Drupal::service('rsvp_list.enabler');
  $node = $form_state->getFormObject()->getEntity();

  if ($form_state->getValue('rsvp_list_enabled')) {
    $enabler->enableNode($node);
  } else {
    $enabler->disableNode($node);
  }
}
